apiVersion: v2
name: prism
description: A Helm chart for Kubernetes
type: application
version: 0.2.1
appVersion: "0.3.0"
dependencies:
  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    version: "16.9.*"
    condition: redis.enabled
  - name: postgresql
    version: "11.2.*"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled