apiVersion: v2
name: prism
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.3.0"
dependencies:
  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    version: "16.9.*"
    condition: redis.enabled