apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prism.batchName" . }}
  labels:
    {{- include "prism.batchLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prism.batchSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prism.batchSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prism.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: batch
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.batch.image }}
          image: "{{ $.Values.global.registry | default .registry }}/{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy | default .pullPolicy }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HELM_CACHE_HOME
              value: /tmp
            - name: HELM_CONFIG_HOME
              value: /tmp
            - name: HELM_DATA_HOME
              value: /tmp
            - name: PRISM_AUTH_SUPER_USER
              value: {{ .Values.initialSuperUser }}
            - name: PRISM_LOG_LEVEL
              value: {{ .Values.global.logLevel | default .Values.batch.logLevel | quote }}
            {{- with .Values.s3 }}
            - name: PRISM_S3_BUCKET
              value: {{ .bucket }}
            - name: PRISM_S3_ENDPOINT
              value: {{ .endpoint }}
            - name: PRISM_S3_PATH_STYLE
              value: {{ .forcepathstyle | quote }}
            - name: PRISM_S3_REGION
              value: {{ .region }}
            {{- end }}
            - name: PRISM_PUBLIC_URL
              value: {{ .Values.url }}
            {{- with .Values.tracing }}
            - name: PRISM_OTEL_ENABLED
              value: {{ .enabled | quote }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .jaegerHost }}
            - name: PRISM_OTEL_SAMPLE_RATE
              value: {{ .sampleRate | quote }}
            {{- end }}
            {{- if .Values.global.postgresql.auth.existingSecret }}
            - name: PRISM_DB_DSN
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.global.postgresql.auth.secretKeys.dsnKey | default "dsn" }}
                  name: {{ .Values.global.postgresql.auth.existingSecret }}
            {{- end }}
            {{- if .Values.global.redis.auth.existingSecret }}
            - name: PRISM_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.global.redis.auth.existingSecretPasswordKey | default "password" }}
                  name: {{ .Values.global.redis.auth.existingSecret }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "prism.coreName" . }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.batch.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
