apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prism.fullname" . }}-rbac
stringData:
  config.yaml: |
    globals:
      SUPER:
        - SUDO
    adapter:
      mode: redis
      redis:
        db: 3
        addrs:
          - {{ .Values.db.redis.addr | default (printf "%s-redis-master" .Release.Name) }}
        password: "$PRISM_REDIS_PASSWORD"
