apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prism.coreName" . }}
stringData:
  {{- if not .Values.oidc.existingSecret }}
  OIDC_CLIENT_ID: {{ .Values.oidc.id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secret }}
  {{- end }}
  {{- if .Values.s3.accesskey }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accesskey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretkey }}
  AWS_REGION: {{ .Values.s3.region }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region }}
  {{- end }}
  {{- if not .Values.global.postgresql.auth.existingSecret }}
  PRISM_DB_DSN: {{ include "prism.primaryDSN" . }}
  {{- end }}
  {{- if .Values.db.dsn.replica }}
  PRISM_DB_DSN_REPLICA: {{ .Values.db.dsn.replica | default "" }}
  {{- end }}
  PRISM_REDIS_ADDR: {{ .Values.db.redis.addr | default (printf "%s-redis-master" .Release.Name) }}
  {{- if not .Values.global.redis.auth.existingSecret }}
  PRISM_REDIS_PASSWORD: {{ .Values.global.redis.password | default .Values.db.redis.password }}
  {{- end }}