{{ if not .Values.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prism.oidcSecretName" . }}
stringData:
  OIDC_CLIENT_ID: {{ .Values.oidc.id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secret }}
{{- end }}