apiVersion: v1
kind: Service
metadata:
  name: {{ include "prism.goproxyName" . }}
  labels:
    {{- include "prism.goproxyLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prism.goproxySelectorLabels" . | nindent 4 }}
