apiVersion: v1
kind: Service
metadata:
  name: {{ include "prism.coreName" . }}
  labels:
    {{- include "prism.coreLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prism.coreSelectorLabels" . | nindent 4 }}
