apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-rbac
data:
  config.yaml: |
    globals:
      SUPER:
        - SUDO
    adapter:
      mode: redis
      redis:
        db: 3
        addrs:
          - redis-master:6379
        password: password