apiVersion: v1
kind: ConfigMap
metadata:
  name: alpine-config
data:
  repositories: |
    http://core3-auto-deploy:8080/api/v1/alpine/-/v3.15/main
    http://core3-auto-deploy:8080/api/v1/alpine/-/v3.15/community
    http://core3-auto-deploy:8080/api/v1/alpine/-/edge/testing
  pip.conf: |
    [global]
    index-url = https://prism3.devel/api/pypi/pypi/simple/
    trusted-host = prism3.devel
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  volumes:
    - name: config
      configMap:
        name: alpine-config
  automountServiceAccountToken: false
  containers:
    - name: app
      image: harbor.dcas.dev/docker.io/library/alpine:3.15
      command:
        - sh
        - -c
        - "tail -f /dev/null"
      volumeMounts:
        - mountPath: /etc/apk/repositories
          name: config
          readOnly: true
          subPath: repositories
        - mountPath: /root/.config/pip/pip.conf
          name: config
          readOnly: true
          subPath: pip.conf