---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpine-config
data:
  repositories: |
    http://core3-auto-deploy:8080/api/v1/alpine/-/v3.15/main
    http://core3-auto-deploy:8080/api/v1/alpine/-/v3.15/community
    http://core3-auto-deploy:8080/api/v1/alpine/-/edge/testing
  pip.conf: |
    [global]
    index-url = https://prism3.devel/api/pypi/pypi/simple/
    trusted-host = prism3.devel
  sources.list: |
    deb http://core3-auto-deploy:8080/api/v1/debian/-/ bullseye main
    deb http://core3-auto-deploy:8080/api/v1/debian/-/ bullseye-security main
    deb http://core3-auto-deploy:8080/api/v1/debian/-/ bullseye-updates main
  settings.xml: |
    <settings xmlns="https://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <localRepository/>
        <interactiveMode/>
        <offline/>
        <pluginGroups/>
        <servers/>
        <mirrors>
            <mirror>
                <id>prism</id>
                <name>Prism</name>
                <url>http://core3-auto-deploy:8080/api/v1/maven/-/</url>
                <mirrorOf>*</mirrorOf>
            </mirror>
        </mirrors>
        <proxies/>
        <profiles/>
        <activeProfiles/>
    </settings>
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  volumes:
    - name: config
      configMap:
        name: alpine-config
  automountServiceAccountToken: false
  containers:
    - name: app
      image: harbor.dcas.dev/docker.io/library/alpine:3.15
      command:
        - sh
        - -c
        - "tail -f /dev/null"
      volumeMounts:
        - mountPath: /etc/apk/repositories
          name: config
          readOnly: true
          subPath: repositories
        - mountPath: /root/.config/pip/pip.conf
          name: config
          readOnly: true
          subPath: pip.conf
        - mountPath: /root/.m2/settings.xml
          name: config
          readOnly: true
          subPath: settings.xml
---
apiVersion: v1
kind: Pod
metadata:
  name: debian
spec:
  volumes:
    - name: config
      configMap:
        name: alpine-config
  automountServiceAccountToken: false
  containers:
    - name: app
      image: harbor.dcas.dev/docker.io/library/debian:bullseye
      command:
        - bash
        - -c
        - "tail -f /dev/null"
      volumeMounts:
        - mountPath: /root/.config/pip/pip.conf
          name: config
          readOnly: true
          subPath: pip.conf
        - mountPath: /root/.m2/settings.xml
          name: config
          readOnly: true
          subPath: settings.xml
        - mountPath: /etc/apt/sources.list
          name: config
          readOnly: true
          subPath: sources.list
