image:
  pullPolicy: Never
podAnnotations:
  app.kubernetes.io/name: core
  app.kubernetes.io/part-of: prism3
env:
  PRISM_AUTH_SUPER_USER: "C=AU,CN=dcas.dev Root CA,L=Canberra,O=dcas.dev,ST=ACT/C=AU,CN=Django Cass,L=Canberra,O=dcas.dev,ST=ACT,emailAddress=django@dcas.dev"
  PRISM_DB_DSN: "user=devstack password=password dbname=prism host=cockroachdb-public.cockroachdb.svc.cluster.local port=26257 sslmode=require"
  PRISM_S3_REGION: "us-east-1"
  PRISM_S3_PATH_STYLE: "true"
  PRISM_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  PRISM_S3_BUCKET: prism
  PRISM_LOG_DEBUG: "true"
  PRISM_PUBLIC_URL: https://prism3.devel
  PRISM_PLUGIN_GO_URL: http://goproxy3-auto-deploy:8080
  AWS_ACCESS_KEY_ID: username
  AWS_SECRET_ACCESS_KEY: password
  HELM_CACHE_HOME: /tmp
  HELM_CONFIG_HOME: /tmp
  HELM_DATA_HOME: /tmp
security:
  podContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
  containerContext:
    runAsNonRoot: true
    runAsGroup: 1001
    runAsUser: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    privileged: false
    capabilities:
      drop:
        - ALL
hpa:
  enabled: false
service:
  externalPort: 8080
  internalPort: 8081
  url: https://prism3.devel
ingress:
  enabled: true
  path: /api
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "iss-kube"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
    nginx.ingress.kubernetes.io/auth-tls-secret: cert-manager/ca-dcas-dev
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  tls:
    enabled: true
    secretName: tls-prism3-core
prometheus:
  metrics: false
livenessProbe:
  path: "/healthz"
  port: 8080
readinessProbe:
  path: "/healthz"
  port: 8080
volumes:
  - name: tmp
    mountPath: /tmp
    config:
      emptyDir: {}
resources:
  requests:
    cpu: 100m
    memory: 200Mi
sidecars:
  - name: captain
    image: harbor.dcas.dev/registry.gitlab.com/av1o/cap10:master
    imagePullPolicy: Always
    env:
      - name: PROXY_TARGET
        value: "http://localhost:8080"
      - name: PROXY_PROBE_PATH
        value: "/healthz"
      - name: PORT
        value: "8081"
    ports:
      - name: http
        containerPort: 8081
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8081
    securityContext:
      runAsNonRoot: true
      runAsGroup: 1001
      runAsUser: 1001
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi
