variables:
  PROJECT_PATH: "goproxy"
  HELM_UPGRADE_VALUES_FILE: ".gitlab/values/goproxy.yaml"
  CNB_SIGN_ENABLED: "false"

container-scanning:
  needs:
    - job: autobuild golang

production:
  resource_group: prod-goproxy
  before_script:
    - kubectl config use-context prism/prism3:kube2-prism
  environment:
    name: prod-goproxy
    kubernetes:
      namespace: prism
  needs:
    - job: autobuild golang
    - job: container-scanning
      optional: true

include:
  - remote: 'https://gitlab.dcas.dev/open-source/gitlab-ci-templates/-/raw/master/auto/Auto-GoMod.gitlab-ci.yml'
