variables:
  AUTO_CNB_RUN_IMAGE: harbor.dcas.dev/docker.io/paketobuildpacks/run:tiny-cnb
  BUILD_KANIKO_DISABLED: "true"
  PROJECT_PATH: "web"
  SOURCE_SUBPATH: "web"
  HELM_UPGRADE_VALUES_FILE: ".gitlab/values/web.yaml"
  BP_STATIC_DIR: "build"
  BP_NODE_VERSION: "~16"
  BP_KEEP_FILES: ".env"
  BP_STATIC_ENV: ".env"
  REPLICAS: 2
  CODE_INTELLIGENCE_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"

container-scanning:
  needs:
    - job: autobuild node

production:
  resource_group: prod-web
  environment:
    name: prod-web
    kubernetes:
      namespace: prism
  needs:
    - job: autobuild node
    - job: container-scanning
      optional: true

include:
  - remote: "https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/Auto-UI.gitlab-ci.yml"
